apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-persistence
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-persistence
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 100
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-auth
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-auth
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 100
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-image
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-image
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 100
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-recommender
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-recommender
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 100
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: teastore-webui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: teastore-webui
  minReplicas: 1
  maxReplicas: 20
  targetCPUUtilizationPercentage: 100